function metrics = compute_comparison_metrics(estimate, truth, elapsedSeconds)
%COMPUTE_COMPARISON_METRICS Summarize horizontal positioning performance.

if ~isnumeric(estimate) || ~isnumeric(truth) || ...
        ~ismatrix(estimate) || ~ismatrix(truth) || ...
        size(estimate, 1) < 2 || size(truth, 1) < 2 || ...
        size(estimate, 2) ~= size(truth, 2) || isempty(estimate) || ...
        any(~isfinite(estimate), 'all') || any(~isfinite(truth), 'all')
    invalid('Estimate and truth must be finite arrays with at least two rows and matching epochs.');
end

if ~isnumeric(elapsedSeconds) || ~isscalar(elapsedSeconds) || ...
        ~isfinite(elapsedSeconds) || elapsedSeconds < 0
    invalid('Elapsed time must be a finite nonnegative scalar in seconds.');
end

errors = vecnorm(estimate(1:2, :) - truth(1:2, :), 2, 1).';
metrics = struct( ...
    'RMSE', sqrt(mean(errors .^ 2)), ...
    'P95', prctile(errors, 95), ...
    'TimeSeconds', elapsedSeconds, ...
    'Errors', errors);
end

function invalid(message)
error('KFVFGO:InvalidMetricsInput', message);
end
